name: CI

on:
  push:
    branches: ['**']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: Der-Floh/Der-Floh/.github/workflows/library-ci.yml@v1
    with:
      project-path: Ico.Reader/Ico.Reader.csproj
      package-id: Ico.Reader
      test-project: Ico.Reader.Test/Ico.Reader.Test.csproj
